image: docker:latest

cache:
  key: ${CI_COMMIT_REF_NAME}
  untracked: true

stages:
- test

test:7.0:
  stage: test
  image: php:7.0
  tags:
  - dev
  - docker
  script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --dev
  - ./vendor/bin/phpunit --coverage-text --colors=never
