# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
cache:
  paths:
    - vendor/

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

stages:
- test

test:7.0:
  stage: test
  image: php:7.0
  tags:
  - dev
  - docker
  script:
  - composer install --dev
  - ./vendor/bin/phpunit --coverage-text --colors=never


