# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
#cache:
#  paths:
#    - vendor/

before_script:
- composer install

stages:
- test

test:7.0:
  stage: test
  image: steveoliver/php-build-test-image:7.0
  tags:
    - dev
    - docker
  script:
    - ./vendor/bin/phpunit

test:7.1:
  stage: test
  image: steveoliver/php-build-test-image:7.1
  tags:
    - dev
    - docker
  script:
    - ./vendor/bin/phpunit

test:7.2:
  stage: test
  image: steveoliver/php-build-test-image:7.2
  tags:
    - dev
    - docker
  script:
    - ./vendor/bin/phpunit

test:7.3:
  stage: test
  image: steveoliver/php-build-test-image:7.3
  tags:
    - dev
    - docker
  script:
    - ./vendor/bin/phpunit

test:7.4:
  stage: test
  image: steveoliver/php-build-test-image:7.4
  tags:
  - dev
  - docker
  script:
  - ./vendor/bin/phpunit
