# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
cache:
  paths:
    - vendor/

before_script:
- php composer.phar install --quiet

stages:
- test

test:7.2:
  stage: test
  image: steveoliver/php-build-test-image:7.2
  tags:
  - dev
  - docker
  script:
  - ./vendor/bin/phpunit


